/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * Generated by: npx tsx supabase/scripts/build-email-templates.ts
 * Source files: supabase/templates/*.html
 *
 * To update templates:
 * 1. Edit HTML files in supabase/templates/
 * 2. Run: pnpm build:email-templates
 * 3. Deploy: supabase functions deploy send-auth-email --no-verify-jwt
 */

export const templates = {
  signup: (data: {
    appName: string
    name: string
    confirmationUrl: string
    currentYear: string
  }): string => `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Confirm your email</title>
  </head>
  <body
    style="
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      padding: 20px;
      max-width: 600px;
      margin: 0 auto;
      background-color: #f5f5f5;
    "
  >
    <div
      style="
        background: #ffffff;
        padding: 32px;
        border-radius: 12px;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
      "
    >
      <div style="text-align: center; margin-bottom: 24px">
        <h1 style="color: #3b82f6; margin: 0">${data.appName}</h1>
      </div>
      <h2 style="color: #1f2937; text-align: center">Confirm your email</h2>
      <p style="color: #4b5563">Hi ${data.name},</p>
      <p style="color: #4b5563">
        Thanks for creating your account. Click the button below to confirm your email address.
      </p>
      <div style="text-align: center; margin: 32px 0">
        <a
          href="${data.confirmationUrl}"
          style="
            display: inline-block;
            background: linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%);
            color: #ffffff;
            padding: 14px 32px;
            border-radius: 8px;
            text-decoration: none;
            font-weight: 600;
            box-shadow: 0 4px 12px rgba(59, 130, 246, 0.4);
          "
        >
          Confirm Email
        </a>
      </div>
      <p style="color: #6b7280; font-size: 14px">This link expires in 24 hours.</p>
      <p style="color: #6b7280; font-size: 14px">
        If you did not create this account, you can safely ignore this email.
      </p>
      <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0" />
      <p style="color: #9ca3af; font-size: 12px; text-align: center">
        &copy; ${data.currentYear} ${data.appName}. All rights reserved.
      </p>
    </div>
  </body>
</html>
`,
  recovery: (data: {
    appName: string
    name: string
    recoveryUrl: string
    currentYear: string
  }): string => `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Reset your password</title>
  </head>
  <body
    style="
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      padding: 20px;
      max-width: 600px;
      margin: 0 auto;
      background-color: #f5f5f5;
    "
  >
    <div
      style="
        background: #ffffff;
        padding: 32px;
        border-radius: 12px;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
      "
    >
      <div style="text-align: center; margin-bottom: 24px">
        <h1 style="color: #3b82f6; margin: 0">${data.appName}</h1>
      </div>
      <h2 style="color: #1f2937; text-align: center">Reset your password</h2>
      <p style="color: #4b5563">Hi ${data.name},</p>
      <p style="color: #4b5563">
        We received a request to reset your password. Click the button below to set a new password.
      </p>
      <div style="text-align: center; margin: 32px 0">
        <a
          href="${data.recoveryUrl}"
          style="
            display: inline-block;
            background: linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%);
            color: #ffffff;
            padding: 14px 32px;
            border-radius: 8px;
            text-decoration: none;
            font-weight: 600;
            box-shadow: 0 4px 12px rgba(59, 130, 246, 0.4);
          "
        >
          Reset Password
        </a>
      </div>
      <p style="color: #6b7280; font-size: 14px">This link expires in 1 hour.</p>
      <p style="color: #6b7280; font-size: 14px">
        If you did not request this, you can safely ignore this email.
      </p>
      <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0" />
      <p style="color: #9ca3af; font-size: 12px; text-align: center">
        &copy; ${data.currentYear} ${data.appName}. All rights reserved.
      </p>
    </div>
  </body>
</html>
`,
  magiclink: (data: {
    appName: string
    name: string
    magicLinkUrl: string
    currentYear: string
  }): string => `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sign in</title>
  </head>
  <body
    style="
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      padding: 20px;
      max-width: 600px;
      margin: 0 auto;
      background-color: #f5f5f5;
    "
  >
    <div
      style="
        background: #ffffff;
        padding: 32px;
        border-radius: 12px;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
      "
    >
      <div style="text-align: center; margin-bottom: 24px">
        <h1 style="color: #3b82f6; margin: 0">${data.appName}</h1>
      </div>
      <h2 style="color: #1f2937; text-align: center">Sign in</h2>
      <p style="color: #4b5563">Hi ${data.name},</p>
      <p style="color: #4b5563">Use the button below to sign in to your account.</p>
      <div style="text-align: center; margin: 32px 0">
        <a
          href="${data.magicLinkUrl}"
          style="
            display: inline-block;
            background: linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%);
            color: #ffffff;
            padding: 14px 32px;
            border-radius: 8px;
            text-decoration: none;
            font-weight: 600;
            box-shadow: 0 4px 12px rgba(59, 130, 246, 0.4);
          "
        >
          Sign In
        </a>
      </div>
      <p style="color: #6b7280; font-size: 14px">This link expires in 1 hour.</p>
      <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0" />
      <p style="color: #9ca3af; font-size: 12px; text-align: center">
        &copy; ${data.currentYear} ${data.appName}. All rights reserved.
      </p>
    </div>
  </body>
</html>
`,
  emailChange: (data: {
    appName: string
    name: string
    confirmationUrl: string
    newEmail: string
    currentYear: string
  }): string => `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Confirm email change</title>
  </head>
  <body
    style="
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      padding: 20px;
      max-width: 600px;
      margin: 0 auto;
      background-color: #f5f5f5;
    "
  >
    <div
      style="
        background: #ffffff;
        padding: 32px;
        border-radius: 12px;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
      "
    >
      <div style="text-align: center; margin-bottom: 24px">
        <h1 style="color: #3b82f6; margin: 0">${data.appName}</h1>
      </div>
      <h2 style="color: #1f2937; text-align: center">Confirm your email change</h2>
      <p style="color: #4b5563">Hi ${data.name},</p>
      <p style="color: #4b5563">
        You requested to change your email to: <strong>${data.newEmail}</strong>
      </p>
      <p style="color: #4b5563">Click the button below to confirm this change.</p>
      <div style="text-align: center; margin: 32px 0">
        <a
          href="${data.confirmationUrl}"
          style="
            display: inline-block;
            background: linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%);
            color: #ffffff;
            padding: 14px 32px;
            border-radius: 8px;
            text-decoration: none;
            font-weight: 600;
            box-shadow: 0 4px 12px rgba(59, 130, 246, 0.4);
          "
        >
          Confirm Change
        </a>
      </div>
      <p style="color: #6b7280; font-size: 14px">
        If you did not request this change, you can safely ignore this email.
      </p>
      <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0" />
      <p style="color: #9ca3af; font-size: 12px; text-align: center">
        &copy; ${data.currentYear} ${data.appName}. All rights reserved.
      </p>
    </div>
  </body>
</html>
`,
  invite: (data: {
    appName: string
    name: string
    confirmationUrl: string
    currentYear: string
    siteUrl: string
  }): string => `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>You're invited</title>
  </head>
  <body
    style="
      font-family:
        -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
    "
  >
    <div style="text-align: center; margin-bottom: 30px">
      <img src="${data.siteUrl}/logo.png" alt="${data.appName}" style="max-width: 150px; height: auto" />
    </div>

    <h1 style="color: #3b82f6; text-align: center; margin-bottom: 24px">You're invited</h1>

    <p>Hi ${data.name},</p>

    <p>
      You've been invited to join <strong>${data.appName}</strong>. Click the button below to accept
      your invitation and create your account:
    </p>

    <div style="text-align: center; margin: 32px 0">
      <a
        href="${data.confirmationUrl}"
        style="
          display: inline-block;
          background-color: #3b82f6;
          color: #ffffff;
          font-size: 16px;
          font-weight: 600;
          padding: 14px 32px;
          text-decoration: none;
          border-radius: 8px;
        "
        >Accept Invitation</a
      >
    </div>

    <p style="color: #6b7280; font-size: 14px">This invitation link will expire in 24 hours.</p>

    <p style="color: #6b7280; font-size: 14px">
      If you didn't expect this invitation, you can safely ignore this email.
    </p>

    <hr style="border: none; border-top: 1px solid #e5e5e5; margin: 32px 0" />

    <p style="color: #9ca3af; font-size: 12px; text-align: center">
      &copy; ${data.currentYear} ${data.appName}. All rights reserved.<br />
      <a href="${data.siteUrl}/privacy" style="color: #9ca3af">Privacy Policy</a> &bull;
      <a href="${data.siteUrl}/terms" style="color: #9ca3af">Terms of Service</a>
    </p>
  </body>
</html>
`,
}

export type TemplateType = keyof typeof templates
