/**
 * Build script to generate email templates module from HTML files.
 *
 * Usage: npx tsx supabase/scripts/build-email-templates.ts
 *    or: pnpm build:email-templates
 *
 * This script reads HTML templates from supabase/templates/ and generates
 * a TypeScript module that can be imported by Edge Functions.
 */

import * as fs from 'fs'
import * as path from 'path'

const TEMPLATES_DIR = './supabase/templates'
const OUTPUT_FILE = './supabase/functions/send-auth-email/templates.generated.ts'

interface TemplateConfig {
  fileName: string
  functionName: string
  params: string[]
}

const templateConfigs: TemplateConfig[] = [
  {
    fileName: 'signup.html',
    functionName: 'signup',
    params: ['appName', 'name', 'confirmationUrl', 'currentYear'],
  },
  {
    fileName: 'recovery.html',
    functionName: 'recovery',
    params: ['appName', 'name', 'recoveryUrl', 'currentYear'],
  },
  {
    fileName: 'magiclink.html',
    functionName: 'magiclink',
    params: ['appName', 'name', 'magicLinkUrl', 'currentYear'],
  },
  {
    fileName: 'email-change.html',
    functionName: 'emailChange',
    params: ['appName', 'name', 'confirmationUrl', 'newEmail', 'currentYear'],
  },
  {
    fileName: 'invite.html',
    functionName: 'invite',
    params: ['appName', 'name', 'confirmationUrl', 'currentYear', 'siteUrl'],
  },
]

function readTemplate(fileName: string): string {
  const filePath = path.join(TEMPLATES_DIR, fileName)
  return fs.readFileSync(filePath, 'utf-8')
}

function convertToTemplateFunction(html: string): string {
  // Convert {{variable}} to ${data.variable}
  return html.replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g, '${data.$1}')
}

function generateTemplatesModule(): void {
  const templateFunctions: string[] = []

  for (const config of templateConfigs) {
    const html = readTemplate(config.fileName)
    const templateContent = convertToTemplateFunction(html)

    const paramsType = config.params.map((p) => `${p}: string`).join('; ')

    templateFunctions.push(`
  ${config.functionName}: (data: { ${paramsType} }): string => \`${templateContent}\`,`)
  }

  const moduleContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * Generated by: npx tsx supabase/scripts/build-email-templates.ts
 * Source files: supabase/templates/*.html
 *
 * To update templates:
 * 1. Edit HTML files in supabase/templates/
 * 2. Run: pnpm build:email-templates
 * 3. Deploy: supabase functions deploy send-auth-email --no-verify-jwt
 */

export const templates = {${templateFunctions.join('')}
}

export type TemplateType = keyof typeof templates
`

  fs.writeFileSync(OUTPUT_FILE, moduleContent)
  console.log(`✅ Generated ${OUTPUT_FILE}`)
  console.log(`   Templates: ${templateConfigs.map((c) => c.functionName).join(', ')}`)
}

// Run
generateTemplatesModule()
